package calculadora;

import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Javier Araujo Mendoza
 */
public class VentanaModificar extends javax.swing.JFrame {

    DefaultTableModel datosElem;
    DefaultTableModel otros;
    int cierre = -1;
    int tabla;
    int indice;

    //Constantes del estado de la ventana
    public static final int ACTIVA = -1;
    public static final int GUARDAR = 1;
    public static final int CANCELAR = 0;

    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar(int tabla, int indice) {
        tituloOtro = tabla > 2 ? "Registros" : "Ficheros";
        initComponents();
        datosElem = (DefaultTableModel) tablaElem.getModel();
        otros = (DefaultTableModel) tablaOtros.getModel();
        this.tabla = tabla;
        this.indice = indice;
    }

    public VentanaModificar(Vector row, int tabla, int indice) {
        tituloOtro = tabla > 2 ? "Registros" : "Ficheros";
        initComponents();
        String nombre = (String) row.elementAt(0);
        if (nombre != null) {
            campoNombre.setText(nombre);
        }
        this.otros = (DefaultTableModel) tablaOtros.getModel();
        List<String> lista = (List<String>) row.elementAt(1);
        if (lista != null) {
            for (int i = 0; i < lista.size(); i++) {
                this.otros.insertRow(i, new String[]{lista.get(i)});
            }
        }
        this.datosElem = (DefaultTableModel) tablaElem.getModel();
        lista = (List<String>) row.elementAt(2);
        if (lista != null) {
            for (int i = 0; i < lista.size(); i++) {
                this.datosElem.insertRow(i, new String[]{lista.get(i)});
            }
        }
        this.tabla = tabla;
        this.indice = indice;
    }

    public Object[] getDatos() {
        Object[] ret = new Object[3];
        ret[0] = campoNombre.getText();
        ret[1] = new ArrayList<String>();
        for (int i = 0; i < otros.getRowCount() - 1; i++) {
            ((List) ret[1]).add(otros.getValueAt(i, 0));
        }
        ret[2] = new ArrayList<String>();
        for (int i = 0; i < datosElem.getRowCount() - 1; i++) {
            ((List) ret[2]).add(datosElem.getValueAt(i, 0));
        }
        return ret;
    }

    public int getCierre() {
        return cierre;
    }

    public int getTabla() {
        return tabla;
    }

    public int getIndice() {
        return indice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorNombre = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaElem = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaOtros = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar elemento");

        contenedorNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        javax.swing.GroupLayout contenedorNombreLayout = new javax.swing.GroupLayout(contenedorNombre);
        contenedorNombre.setLayout(contenedorNombreLayout);
        contenedorNombreLayout.setHorizontalGroup(
            contenedorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenedorNombreLayout.setVerticalGroup(
            contenedorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaElem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Clic para añadir..."}
            },
            new String [] {
                "Datos elementales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int column)
            {
                if (row == this.getRowCount()-1) return false;
                else return true;
            }

        });
        tablaElem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaElem.getTableHeader().setReorderingAllowed(false);
        tablaElem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        tablaElem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaElem);
        if (tablaElem.getColumnModel().getColumnCount() > 0) {
            tablaElem.getColumnModel().getColumn(0).setResizable(false);
        }

        tablaOtros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Clic para añadir..."}
            },
            new String [] {
                tituloOtro
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int column)
            {
                if (row == this.getRowCount()-1) return false;
                else return true;
            }

        });
        tablaOtros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaOtros.getTableHeader().setReorderingAllowed(false);
        tablaOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        tablaOtros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tablaOtros);
        if (tablaOtros.getColumnModel().getColumnCount() > 0) {
            tablaOtros.getColumnModel().getColumn(0).setResizable(false);
        }

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contenedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        //Obtener la tabla donde se ha producido el evento
        JTable tabSeleccion = (JTable) evt.getSource();
        DefaultTableModel tm = (DefaultTableModel) tabSeleccion.getModel();
        //Seleccionar el ítem
        int seleccion = tabSeleccion.rowAtPoint(evt.getPoint());
        tabSeleccion.setRowSelectionInterval(seleccion, seleccion);
        
        if (seleccion == tm.getRowCount() - 1) {
            if (evt.getButton() == 1) {
                tm.insertRow(seleccion, new String[]{"Nuevo dato"});
            }
        } else {
            if (evt.getButton() != 1) {
                tm.removeRow(seleccion);
            } else {
                if ("Nuevo dato".equals((String) tm.getValueAt(seleccion, 0))) {
                    tm.setValueAt("", seleccion, 0);
                }
                tabSeleccion.editCellAt(seleccion, 0);
            }
        }
    }//GEN-LAST:event_tablaMousePressed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        //Obtener la tabla donde se ha producido el evento
        JTable tabSeleccion = (JTable) evt.getSource();
        DefaultTableModel tm = (DefaultTableModel) tabSeleccion.getModel();
        //Seleccionar el ítem
        int seleccion = tabSeleccion.getSelectedRow();
        int tecla = evt.getKeyCode();

        if (seleccion == tm.getRowCount() - 1) {
            switch (tecla) {
                case KeyEvent.VK_ENTER -> //Actúa como si se hubiese clicado
                    tm.insertRow(seleccion, new String[]{"Nuevo dato"});
                case KeyEvent.VK_DELETE -> {//Borra la lista
                    while (tm.getRowCount() > 1) {
                        tm.removeRow(0);
                    }
                }
            }
        } else if (seleccion != -1) {
            if (tecla == KeyEvent.VK_DELETE) {
                tm.removeRow(seleccion);
            }
        }
    }//GEN-LAST:event_tablaKeyPressed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        cierre = GUARDAR;
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        cierre = CANCELAR;
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_bCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel contenedorNombre;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaElem;
    private String tituloOtro = "Más datos";
    private javax.swing.JTable tablaOtros;
    // End of variables declaration//GEN-END:variables
}
